//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webform.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string ID_custom { get; set; }
        public string name_custom { get; set; }
        public string address_custom { get; set; }
        public string phone_number { get; set; }
        public string product_name { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<double> sum_price { get; set; }
        public Nullable<System.DateTime> date_order { get; set; }
        public string method { get; set; }
        public string ID_order { get; set; }
        public string status { get; set; }
        public string status_order { get; set; }
    }
}
