//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webforrm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ID { get; set; }
        public string name_product { get; set; }
        public string image { get; set; }
        public string descrip { get; set; }
        public Nullable<int> quality { get; set; }
        public Nullable<double> price { get; set; }
        public string category { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
